---
title: "Data Cleaning & Descriptives"
author: "Brianna Cirillo"
output: html_notebook
---
# Matching the bouy data to the other data collected 
```{r}
hilo <- hbb_wku_h_xts
hilo <- data.frame(date=index(hilo), coredata(hilo))
hilo <- hilo[529:54816,]
hilo
# which(hilo$date=="2010-10-23 00:00:00") = index 529 

# which(hilo$date=="2016-12-31 23:00:00") = index 54816
```

```{r}
length(hilo[,1]) # we are left with 54288 lines of data

54816 - length(hilo[,1]) # we lost 528 values 
```

# Changing column names 
```{r}
# removing columns that we are not using 
hilo$date.2 <- NULL # another date column
hilo$date.1 <- NULL # another date column
hilo$BGARFU <- NULL # ?
hilo$DOmgL <- NULL # dissolved oxygen
hilo$Doper <- NULL # dissolved oxygen
hilo$PAR1 <- NULL # ?
hilo$pH <- NULL # pH
hilo$NTU <- NULL # a different measurement for turbitity
hilo$DOper10 <- NULL # dissolved oxygen

# colnames(hilo) <- c("Date", "cfs", "RiverFlow-cumec", "LogRiverFlow-cumec", "Chlorophyll-RFU", "Salinity-PPT", "Temp-C", "chlorophyll-calibrator", "Turbidity-NTU")
# does not work ???

hilo
```
# Descriptives: plots of variables over time
```{r}
length(hilo$logcms[which(is.na(hilo$logcms)==TRUE)]) # 12 NAs 


RiverFlow <- ggplot(hilo,  aes(x = date, y = as.numeric(logcms))) + 
  geom_line()

print(RiverFlow + ggtitle("River Flow")+labs(x="Time", y = "Log River Flow - cubic meters per second"))

```

```{r}
length(hilo$ChlRFU[which(is.na(hilo$ChlRFU)==TRUE)]) # 20464 NAs


CHL <- ggplot(hilo,  aes(x = date, y = as.numeric(ChlRFU))) + 
  geom_line()

print(CHL + ggtitle("Chlorophyll ")+labs(x="Time", y = "Chlorophyll  - relative fluorescence units (RFU)"))

```

```{r}
length(hilo$Corr.NTU[which(is.na(hilo$Corr.NTU)==TRUE)]) #15012 NAs

TURB <- ggplot(hilo,  aes(x = date, y = as.numeric(Corr.NTU))) + 
  geom_line()

print(TURB + ggtitle("Turbidity ")+labs(x="Time", y = "Turbidity - Nephelometric Turbidity Units (NTU)"))

```

```{r}
length(hilo$saltppt[which(is.na(hilo$saltppt)==TRUE)]) #11330 NAs

SALT <- ggplot(hilo,  aes(x = date, y = as.numeric(saltppt))) + 
  geom_line()

print(SALT + ggtitle("Salinity")+labs(x="Time", y = "Salinity - unit parts per thousand (PPT)"))

```

# Histograms
```{r}
hist(as.numeric(hilo$logcms), main = "Histogram of Log River Flow", xlab = "Log River Flow")

```

```{r}
hist(as.numeric(hilo$ChlRFU), main = "Histogram of Chlorophyll", xlab = "Chlorophyll  - relative fluorescence units (RFU)")

```

```{r}
hist(as.numeric(hilo$Corr.NTU), main = "Histogram of Turbidity", xlab = "Turbidity - Nephelometric Turbidity Units (NTU)")
```

```{r}
hist(as.numeric(hilo$saltppt), main = "Histogram of Salinity", xlab = "Salinity - unit parts per thousand (PPT)")
```

# Denisty Plots

```{r}
rfdens <- ggplot(hilo,  aes(x = as.numeric(logcms))) + 
  geom_density()

rfdens
```


```{r}
chldens <- ggplot(hilo,  aes(x = as.numeric(ChlRFU))) + 
  geom_density()

chldens
```

```{r}
turbdens <- ggplot(hilo,  aes(x = as.numeric(Corr.NTU))) + 
  geom_density()

turbdens
```

```{r}
saltdens <- ggplot(hilo,  aes(x = as.numeric(saltppt))) + 
  geom_density()

saltdens
```




















