---
title: "R Notebook"
output: html_notebook
---

# Example

```{r}
#install.packages("vars") 
#install.packages("astsa") 
library(vars)
library(astsa)

#creates a vector of response variables
x = cbind(cmort, tempr, part) 

#VAR command does estimation of AR models using ordinary least squares while simultaneously fitting the trend, intercept, and ARIMA model
plot.ts(x , main = "", xlab = "")
fitvar1= VAR(x, p=1, type="both")
summary(fitvar1)
```

```{r}
# Removing NAs
hilo2015[is.na(hilo2015)] <- 0
sum(is.na(hilo2015))

# Saving as numeric vectors
riverflow <- as.numeric(hilo2015.fixed$cms)
chlorophyll <- as.numeric(hilo2015.fixed$ChlRF)
dissolved_o2 <- as.numeric(hilo2015.fixed$Doper)
salinity <- as.numeric(hilo2015.fixed$saltppt)
temp <- as.numeric(hilo2015.fixed$TempC)
turbidity <- as.numeric(hilo2015.fixed$Corr.NTU)

#creates a vector of response variables
h_chlorophyll <-  cbind(riverflow, chlorophyll)
h_dissolvedo2 <- cbind(riverflow, dissolved_o2)
h_salinity <- cbind(riverflow, salinity)
h_temp <- cbind(riverflow, temp)
h_turbidity <- cbind(riverflow, turbidity)

#VAR command does estimation of AR models using ordinary least squares while simultaneously fitting the trend, intercept, and ARIMA model
#plot.ts(h , main = "", xlab = "")
fitvar1_chlorophyll= VAR(h_chlorophyll, p=1, type="none")
summary(fitvar1_chlorophyll)

fitvar1_dissolvedo2= VAR(h_dissolvedo2, p=1, type="none")
summary(fitvar1_dissolvedo2)

fitvar1_salinity= VAR(h_salinity, p=1, type="none")
summary(fitvar1_salinity)

fitvar1_temp= VAR(h_temp, p=1, type="none")
summary(fitvar1_temp)

fitvar1_turbidity= VAR(h_turbidity, p=1, type="none")
summary(fitvar1_turbidity)
```
  

```{r}
# 2nd Lag
fitvar2_chlorophyll= VAR(h_chlorophyll, p=2, type="none")
summary(fitvar2_chlorophyll)

fitvar2_dissolvedo2= VAR(h_dissolvedo2, p=2, type="none")
summary(fitvar2_dissolvedo2)

fitvar2_salinity= VAR(h_salinity, p=2, type="none")
summary(fitvar2_salinity)

fitvar2_temp= VAR(h_temp, p=2, type="none")
summary(fitvar2_temp)

fitvar2_turbidity= VAR(h_turbidity, p=2, type="none")
summary(fitvar2_turbidity)
```
```{r}
# 3rd Lag
fitvar3_chlorophyll= VAR(h_chlorophyll, p=3, type="none")
summary(fitvar3_chlorophyll)

fitvar3_dissolvedo2= VAR(h_dissolvedo2, p=3, type="none")
summary(fitvar3_dissolvedo2)

fitvar3_salinity= VAR(h_salinity, p=3, type="none")
summary(fitvar3_salinity)

fitvar3_temp= VAR(h_temp, p=3, type="none")
summary(fitvar3_temp)

fitvar3_turbidity= VAR(h_turbidity, p=3, type="none")
summary(fitvar3_turbidity)
```

```{r}
# Ask about what this is

acf(residuals(fitvar2_salinity)[,1], plot = FALSE)
acf(residuals(fitvar2_salinity)[,1], plot = TRUE, ylim=c(0,0.15))
# acf(residuals(fitvar2)[,2])
# acf(residuals(fitvar2)[,3])
# acf(residuals(fitvar2)[,4])
# acf(residuals(fitvar2)[,5])
# acf(residuals(fitvar2)[,6])
?acf


2/sqrt(length(salinity))
```
 
```{r}
cmsturb <- irf(fitvar2, impulse = "riverflow", response = "turbidity", n.ahead = 8, ortho = FALSE, runs = 1000)
cmsturb
plot(cmsturb)
```

```{r}
cmssalin <- irf(fitvar2, impulse = "riverflow", response = "salinity", n.ahead = 8, ortho = FALSE, runs = 1000)
cmssalin
plot(cmssalin)
```


```{r}
cmschlor <- irf(fitvar2, impulse = "riverflow", response = "chlorophyll", n.ahead = 8, ortho = FALSE, runs = 1000)
cmschlor
plot(cmschlor)
```

```{r}
cmsdisso2 <- irf(fitvar2, impulse = "riverflow", response = "dissolved_o2", n.ahead = 8, ortho = FALSE, runs = 1000)
cmsdisso2
plot(cmsdisso2)
```

```{r}
cmstemp <- irf(fitvar2, impulse = "riverflow", response = "temp", n.ahead = 8, ortho = FALSE, runs = 1000)
cmstemp
plot(cmstemp)
```

```{r}
#install.packages("smooth")
library(smooth)
hilo2015$logcms <- NULL
hilo2015$chlcal <- NULL
hilo2015$ChlRF <- NULL
which(is.na(hilo2015))
var.hilo2015 <- hilo2015[-c(which(is.na(hilo2015))),]  
sum(is.na(var.hilo2015))
hilo2015 <- na.omit(hilo2015)
sum(is.na(var.hilo2015))

hilo2015.fixed <- na.omit(hilo2015)
sum(is.na(hilo2015.fixed))
```

 
























