---
title: "Impulse Response Example for Vector Autoregressive Models"
output: html_notebook
---

Main Purpose: describes the evolution of a model’s variables in reaction to a shock in one or more variables

Data: quarterly, seasonally adjusted time series for West German fixed investment, disposable income, and consumption expenditures in billions of DM from 1960 Q1 to 1982 Q4

```{r}
# Download data
data <- read.table("http://www.jmulti.de/download/datasets/e1.dat", skip = 6, header = TRUE)

# Only use the first 76 observations so that there are 73 observations
# left for the estimated VAR(2) model after taking first differences.
data <- data[1:76, ]

# Convert to time series object
data <- ts(data, start = c(1960, 1), frequency = 4)

# Take logs and differences
data <- diff(log(data))

# Plot data
plot(data,  main = "Dataset E1 from Lütkepohl (2007)")
```

```{r}
# Install package
#install.packages("vars")

# Load package
library(vars)

# Estimate model
model <- VAR(data, p = 2, type = "const")

# Look at summary statistics
summary(model)
```

```{r}
feir <- irf(model, impulse = "income", response = "cons",
             n.ahead = 8, ortho = FALSE, runs = 1000)

plot(feir)
```


```{r}
# Calculate summary statistics
model_summary <- summary(model)

# Obtain variance-covariance matrix
model_summary$covres
```

```{r}
model_summary$corres
```

```{r}
t(chol(model_summary$covres))
```

```{r}
oir <- irf(model, impulse = "income", response = "cons",
           n.ahead = 8, ortho = TRUE, runs = 1000, seed = 12345)

plot(oir)
```



























